version: '3'
services:
  postgres:
    container_name: pgs
    restart: always
    image: postgres:latest
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
